server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 123456