server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zy_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 123456